"""Standard runtime errors. Never fake success."""

CAPABILITY_UNAVAILABLE = "CAPABILITY_UNAVAILABLE"
CAPABILITY_RESTRICTED_BY_OS = "CAPABILITY_RESTRICTED_BY_OS"
PERMISSION_REQUIRED = "PERMISSION_REQUIRED"
USER_APPROVAL_REQUIRED = "USER_APPROVAL_REQUIRED"
AUTHENTICATION_REQUIRED = "AUTHENTICATION_REQUIRED"
CONNECTOR_NOT_CONNECTED = "CONNECTOR_NOT_CONNECTED"
NETWORK_REQUIRED = "NETWORK_REQUIRED"
DEVICE_OFFLINE = "DEVICE_OFFLINE"
ACTION_FAILED = "ACTION_FAILED"
VERIFICATION_FAILED = "VERIFICATION_FAILED"
KILL_SWITCH = "KILL_SWITCH"

ALL_ERROR_CODES = (
    CAPABILITY_UNAVAILABLE,
    CAPABILITY_RESTRICTED_BY_OS,
    PERMISSION_REQUIRED,
    USER_APPROVAL_REQUIRED,
    AUTHENTICATION_REQUIRED,
    CONNECTOR_NOT_CONNECTED,
    NETWORK_REQUIRED,
    DEVICE_OFFLINE,
    ACTION_FAILED,
    VERIFICATION_FAILED,
    KILL_SWITCH,
)
